### ISSUE TITLE
---- ---- ----

### ISSUE THREAD

**Issue by lucidyan** [microsoft/referencesource#130] opened 2020-02-01 16:38 UTC
It looks like you replace with regex some words. Please, comment why it happened and return it back, because it looks very strange and uninformative.

You can see a lot of examples of this in file:
https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Data.Entity.Design/System/Data/Entity/Design/PluralizationService/EnglishPluralizationService.cs#L39-L52

___
Why I think it very strange:
![image](https://user-images.githubusercontent.com/5789108/73595447-fd11cf80-4529-11ea-8bc5-998eb74c0f4b.png)
___

All occurencies in this repo:
https://github.com/microsoft/referencesource/search?l=C%23&q=----

More about this situation:
https://thedailywtf.com/articles/comments/microsoft-s-english-pluralization-service

**Comment by KalleOlaviNiemitalo** [comment] 2020-02-20 15:27
Duplicate of #68 and #111

**Comment by geoff-m** [comment] 2020-11-15 10:10
It is clear that some or all occurrences of the words "race", "weed", "Persian", "Taiwan", and "culture", are among those that have been replaced. But annoyingly often, it isn't clear what word used to be there.

**Comment by terrajobst** [comment] 2023-02-17 20:41
Closed as duplicate of #68

**Closed by terrajobst** 2023-02-17 20:41 UTC
Labels: Infrastructure
