### ISSUE TITLE
Why there are 4 dashes in comments instead of words?

### ISSUE THREAD

**Issue by Otaman** [microsoft/referencesource#111] opened 2019-07-14 16:34 UTC
I was wondered to see ---- instead some words in code's documentation. The dashes make it harder to understand the comments.

For example:
https://github.com/microsoft/referencesource/blob/e0bf122d0e52a42688b92bb4be2cfd66ca3c2f07/mscorlib/system/threading/Tasks/Task.cs#L273

**Comment by KalleOlaviNiemitalo** [comment] 2019-08-16 16:19
I guess Microsoft automatically censors swear words from public sources and "race" somehow ended up in the blacklist.

**Comment by KalleOlaviNiemitalo** [comment] 2019-08-16 16:45
Duplicate of #68

**Comment by terrajobst** [comment] 2023-02-17 20:42
Closed as duplicate of #68.

**Closed by terrajobst** 2023-02-17 20:42 UTC
Labels: Infrastructure
